#
# Make a slighly hacked version of the "openssl" command line executable
# We needed to do this for ICC8.0 because on many platforms openssl 0.9.8
# won't initialize without /dev/random. Mess around with all the build 
# machines, or build our own OpenSSL with the ICC TRNG in it - 
# - tough call.
# 

include $(ICC_ROOT)/icc/opensslver.mk

DEFAULT_APP_DIR        		= $(OSSL_DIR)/tmp32dll$($(OPSYS)_$(CONFIG)_OSSL_SUFFIX)
DEFAULT_LIB_DIR             = $(OSSL_DIR)/out32dll$($(OPSYS)_$(CONFIG)_OSSL_SUFFIX)
DEFAULT_SLIBCRYPTO          = $(CRYPTOOBJ)
DEFAULT_SLIBSSL             = $(SSLOBJ)
DEFAULT_OPENSSL_LIBS 		= ws2_32.lib

$(OPSYS)_APP_DIR        	= $(DEFAULT_APP_DIR)
$(OPSYS)_LIB_DIR            = $(DEFAULT_LIB_DIR)
$(OPSYS)_SLIBCRYPTO         = $(DEFAULT_SLIBCRYPTO)
$(OPSYS)_SLIBSSL            = $(DEFAULT_SLIBSSL)
$(OPSYS)_OPENSSL_LIBS 		= $(DEFAULT_OPENSSL_LIBS)

# Directory the "openssl" executable objects are in
UNIX_APP_DIR            	= $(OSSL_DIR)/apps
# Extra libs "openssl" needs over those we provide by default 
# -lnsl -lsocket etc on various platforms
#
UNIX_SLIBCRYPTO              	= $(OSSL_DIR)/libcrypto.a
UNIX_SLIBSSL			= $(OSSL_DIR)/libssl.a
UNIX_OPENSSL_LIBS               = $(UNIX_SLIBSSL) $(UNIX_SLIBCRYPTO) 


WIN_APP_DIR        		= $(OSSL_DIR)/tmp32dll$($(OPSYS)_$(CONFIG)_OSSL_SUFFIX)
WIN_LIB_DIR                     = $(OSSL_DIR)/out32dll$($(OPSYS)_$(CONFIG)_OSSL_SUFFIX)
WIN_SLIBCRYPTO                  = $(CRYPTOOBJ)
WIN_SLIBSSL                     = $(SSLOBJ)


WIN_OPENSSL_LIBS                = wsock32.lib

WIN32_APP_DIR      		= $(WIN_APP_DIR)
WIN32_OPENSSL_LIBS 		= $(WIN_OPENSSL_LIBS)
WIN32_SLIBCRYPTO                = $(WIN_SLIBCRYPTO)
WIN32_SLIBSSL                   = $(WIN_SLIBSSL)

WIN64_APP_DIR      		= $(WIN_APP_DIR)
WIN64_OPENSSL_LIBS 		= ws2_32.lib
WIN64_SLIBCRYPTO                = $(WIN_LIB_DIR)/libeay32.lib
WIN64_SLIBSSL                   = $(WIN_LIB_DIR)/ssleay32.lib
#WIN64_SLIBCRYPTO                = $(WIN_SLIBCRYPTO)
#WIN64_SLIBSSL                   = $(WIN_SLIBSSL)

WIN64_AMD_APP_DIR      		= $(WIN_APP_DIR)
WIN64_AMD_OPENSSL_LIBS 		= $(WIN_OPENSSL_LIBS)
WIN64_AMD_SLIBCRYPTO            = $(WIN64_AMD_CRYPTOOBJ)
WIN64_AMD_SLIBSSL               = $(SSLOBJ)

WIN32_VS2013_APP_DIR      	= $(WIN_APP_DIR)
WIN32_VS2013_OPENSSL_LIBS 	= $(WIN_OPENSSL_LIBS)
WIN32_VS2013_SLIBCRYPTO		= $(WIN_SLIBCRYPTO)
WIN32_VS2013_SLIBSSL		= $(WIN_SLIBSSL)

WIN64_AMD_VS2013_APP_DIR      	= $(WIN_APP_DIR)
WIN64_AMD_VS2013_OPENSSL_LIBS 	= $(WIN_OPENSSL_LIBS)
WIN64_AMD_VS2013_SLIBCRYPTO	= $(WIN64_AMD_CRYPTOOBJ)
WIN64_AMD_VS2013_SLIBSSL	= $(SSLOBJ)

WIN64_VS2022_APP_DIR      	= $(WIN_APP_DIR)
WIN64_VS2022_OPENSSL_LIBS 	= $(WIN_OPENSSL_LIBS)
WIN64_VS2022_SLIBCRYPTO	= $(WIN64_AMD_CRYPTOOBJ)
WIN64_VS2022_SLIBSSL	= $(SSLOBJ)

LINUX_APP_DIR			= $(UNIX_APP_DIR)
LINUX_OPENSSL_LIBS              = $(UNIX_OPENSSL_LIBS)
LINUX_SLIBCRYPTO                = $(UNIX_SLIBCRYPTO)
LINUX_SLIBSSL                   = $(UNIX_SLIBSSL)

LINUXDL_APP_DIR			= $(LINUX_APP_DIR)
LINUXDL_OPENSSL_LIBS            = $(LINUX_OPENSSL_LIBS)
LINUXDL_SLIBCRYPTO              = $(UNIX_SLIBCRYPTO)
LINUXDL_SLIBSSL                 = $(UNIX_SLIBSSL)

IA64_LINUX_APP_DIR             	= $(LINUX_APP_DIR)
IA64_LINUX_OPENSSL_LIBS         = $(LINUX_OPENSSL_LIBS)
IA64_LINUX_SLIBCRYPTO           = $(UNIX_SLIBCRYPTO)
IA64_LINUX_SLIBSSL              = $(UNIX_SLIBSSL)

ARM_LINUX_APP_DIR        	= $(LINUX_APP_DIR)
ARM_LINUX_OPENSSL_LIBS   	= $(LINUX_OPENSSL_LIBS)
ARM_LINUX_SLIBCRYPTO          	= $(UNIX_SLIBCRYPTO)
ARM_LINUX_SLIBSSL             	= $(UNIX_SLIBSSL)

ARM64_LINUX_APP_DIR        	= $(LINUX_APP_DIR)
ARM64_LINUX_OPENSSL_LIBS   	= $(LINUX_OPENSSL_LIBS)
ARM64_LINUX_SLIBCRYPTO          = $(UNIX_SLIBCRYPTO)
ARM64_LINUX_SLIBSSL             = $(UNIX_SLIBSSL)

AMD64_LINUX_APP_DIR        	= $(LINUX_APP_DIR)
AMD64_LINUX_OPENSSL_LIBS   	= $(LINUX_OPENSSL_LIBS)
AMD64_LINUX_SLIBCRYPTO          = $(UNIX_SLIBCRYPTO)
AMD64_LINUX_SLIBSSL             = $(UNIX_SLIBSSL)

PPC_LINUX_APP_DIR        	= $(LINUX_APP_DIR)
PPC_LINUX_OPENSSL_LIBS   	= $(LINUX_OPENSSL_LIBS)
PPC_LINUX_SLIBCRYPTO            = $(UNIX_SLIBCRYPTO)
PPC_LINUX_SLIBSSL               = $(UNIX_SLIBSSL)

PPC64_LINUX_APP_DIR        	= $(LINUX_APP_DIR)
PPC64_LINUX_OPENSSL_LIBS   	= $(LINUX_OPENSSL_LIBS)
PPC64_LINUX_SLIBCRYPTO          = $(UNIX_SLIBCRYPTO)
PPC64_LINUX_SLIBSSL             = $(UNIX_SLIBSSL)

PPC64LE_LINUX_APP_DIR        	= $(LINUX_APP_DIR)
PPC64LE_LINUX_OPENSSL_LIBS   	= $(LINUX_OPENSSL_LIBS)
PPC64LE_LINUX_SLIBCRYPTO        = $(UNIX_SLIBCRYPTO)
PPC64LE_LINUX_SLIBSSL           = $(UNIX_SLIBSSL)

S390_LINUX_APP_DIR        	= $(LINUX_APP_DIR)
S390_LINUX_OPENSSL_LIBS   	= $(LINUX_OPENSSL_LIBS)
S390_LINUX_SLIBCRYPTO           = $(UNIX_SLIBCRYPTO)
S390_LINUX_SLIBSSL              = $(UNIX_SLIBSSL)

S390X_LINUX_APP_DIR        	= $(LINUX_APP_DIR)
S390X_LINUX_OPENSSL_LIBS   	= $(LINUX_OPENSSL_LIBS)
S390X_LINUX_SLIBCRYPTO          = $(UNIX_SLIBCRYPTO)
S390X_LINUX_SLIBSSL             = $(UNIX_SLIBSSL)

AIX_APP_DIR			= $(UNIX_APP_DIR)
AIX_OPENSSL_LIBS            	= $(UNIX_OPENSSL_LIBS)
AIX_SLIBCRYPTO                	= $(OSSL_DIR)/libcrypto_a.a
AIX_SLIBSSL                   	= $(OSSL_DIR)/libssl_a.a

AIX64_APP_DIR					= $(AIX_APP_DIR)
AIX64_OPENSSL_LIBS            	= $(AIX_OPENSSL_LIBS)
AIX64_SLIBCRYPTO                = $(OSSL_DIR)/libcrypto_a.a
AIX64_SLIBSSL                   = $(OSSL_DIR)/libssl_a.a

OSX_APP_DIR			= $(UNIX_APP_DIR)
OSX_OPENSSL_LIBS            	= $(UNIX_OPENSSL_LIBS)
OSX_SLIBCRYPTO                	= $(UNIX_SLIBCRYPTO)
OSX_SLIBSSL                   	= $(UNIX_SLIBSSL)

OSX_PPC_APP_DIR			= $(OSX_APP_DIR)
OSX_PPC_OPENSSL_LIBS		= $(OSX_OPENSSL_LIBS)
OSX_PPC_SLIBCRYPTO		= $(OSX_SLIBCRYPTO)
OSX_PPC_SLIBSSL			= $(OSX_SLIBSSL)

OSX_X86_APP_DIR			= $(OSX_APP_DIR)
OSX_X86_OPENSSL_LIBS		= $(OSX_OPENSSL_LIBS)
OSX_X86_SLIBCRYPTO		= $(OSX_SLIBCRYPTO)
OSX_X86_SLIBSSL			= $(OSX_SLIBSSL)

OSX_PPC64_APP_DIR		= $(OSX_APP_DIR)
OSX_PPC64_OPENSSL_LIBS		= $(OSX_OPENSSL_LIBS)
OSX_PPC64_SLIBCRYPTO		= $(OSX_SLIBCRYPTO)
OSX_PPC64_SLIBSSL		= $(OSX_SLIBSSL)

OSX_X86_64_APP_DIR		= $(OSX_APP_DIR)
OSX_X86_64_OPENSSL_LIBS		= $(OSX_OPENSSL_LIBS)
OSX_X86_64_SLIBCRYPTO		= $(OSX_SLIBCRYPTO)
OSX_X86_64_SLIBSSL		= $(OSX_SLIBSSL)



OSX_FAT4_APP_DIR		= $(UNIX_APP_DIR)
OSX_FAT4_OPENSSL_LIBS           = $(UNIX_OPENSSL_LIBS)
OSX_FAT4_SLIBCRYPTO		= $(UNIX_SLIBCRYPTO)
OSX_FAT4_SLIBSSL		= $(UNIX_SLIBSSL)

OSXV9_APP_DIR		= $(OSX_APP_DIR)
OSXV9_OPENSSL_LIBS		= $(OSX_OPENSSL_LIBS)
OSXV9_SLIBCRYPTO		= $(OSX_SLIBCRYPTO)
OSXV9_SLIBSSL		= $(OSX_SLIBSSL)

OSX_ARM64_APP_DIR		= $(OSX_APP_DIR)
OSX_ARM64_OPENSSL_LIBS	= $(OSX_OPENSSL_LIBS)
OSX_ARM64_SLIBCRYPTO	= $(OSX_SLIBCRYPTO)
OSX_ARM64_SLIBSSL		= $(OSX_SLIBSSL)


SUN_APP_DIR			= $(UNIX_APP_DIR)
SUN_OPENSSL_LIBS            	= -lsocket -lnsl
SUN_SLIBCRYPTO			= $(UNIX_SLIBCRYPTO)
SUN_SLIBSSL			= $(UNIX_SLIBSSL)


SUN_X86_APP_DIR   		= $(SUN_APP_DIR)
SUN_X86_OPENSSL_LIBS 		= $(SUN_OPENSSL_LIBS)
SUN_X86_SLIBCRYPTO		= $(UNIX_SLIBCRYPTO)
SUN_X86_SLIBSSL			= $(UNIX_SLIBSSL)

SUN64_APP_DIR   		= $(SUN_APP_DIR)
SUN64_OPENSSL_LIBS 		= $(SUN_OPENSSL_LIBS)
SUN64_SLIBCRYPTO                = $(UNIX_SLIBCRYPTO)
SUN64_SLIBSSL                   = $(UNIX_SLIBSSL)

SUN_AMD64_APP_DIR   		= $(SUN_APP_DIR)
SUN_AMD64_OPENSSL_LIBS 		= $(SUN_OPENSSL_LIBS)
SUN_AMD64_SLIBCRYPTO 		= $(UNIX_SLIBCRYPTO)
SUN_AMD64_SLIBSSL		= $(UNIX_SLIBSSL)

HPUX_APP_DIR			= $(UNIX_APP_DIR)
HPUX_OPENSSL_LIBS            	=  $(UNIX_OPENSSL_LIBS)
HPUX_SLIBCRYPTO			= $(UNIX_SLIBCRYPTO)
HPUX_SLIBSSL			= $(UNIX_SLIBSSL)

HPUX64_APP_DIR			= $(HPUX_APP_DIR)
HPUX64_OPENSSL_LIBS         	= $(HPUX_OPENSSL_LIBS)
HPUX64_SLIBCRYPTO		= $(UNIX_SLIBCRYPTO)
HPUX64_SLIBSSL			= $(UNIX_SLIBSSL)

IA64_HPUX_APP_DIR		= $(HPUX_APP_DIR)
IA64_HPUX_OPENSSL_LIBS         	= $(HPUX_OPENSSL_LIBS)
IA64_HPUX_SLIBCRYPTO		= $(UNIX_SLIBCRYPTO)
IA64_HPUX_SLIBSSL		= $(UNIX_SLIBSSL)

IA64_HPUX64_APP_DIR		= $(HPUX_APP_DIR)
IA64_HPUX64_OPENSSL_LIBS   	= $(HPUX_OPENSSL_LIBS)
IA64_HPUX64_SLIBCRYPTO		= $(UNIX_SLIBCRYPTO)
IA64_HPUX64_SLIBSSL		= $(UNIX_SLIBSSL)

OS400_APP_DIR			= $(UNIX_APP_DIR)
OS400_OPENSSL_LIBS            	= $(UNIX_OPENSSL_LIBS)

OS400X_APP_DIR			= $(UNIX_APP_DIR)
OS400X_OPENSSL_LIBS            	= $(UNIX_OPENSSL_LIBS)
#
#  ZOS 64 bit
#
ZOS_APP_DIR			= $(UNIX_APP_DIR)
ZOS_OPENSSL_LIBS		= $(UNIX_OPENSSL_LIBS)
ZOS_SLIBCRYPTO			= $(UNIX_SLIBCRYPTO)
ZOS_SLIBSSL			= $(UNIX_SLIBSSL)

#
#  ZOS 64 bit ASCII mode
#
ZOSA_APP_DIR			= $(UNIX_APP_DIR)
ZOSA_OPENSSL_LIBS		= $(UNIX_OPENSSL_LIBS)
ZOSA_SLIBCRYPTO			= $(UNIX_SLIBCRYPTO)
ZOSA_SLIBSSL			= $(UNIX_SLIBSSL)

#
# ZOS 31 bit
#
ZOS31_APP_DIR			= $(UNIX_APP_DIR)
ZOS31_OPENSSL_LIBS		= $(UNIX_OPENSSL_LIBS)
ZOS31_SLIBCRYPTO		= $(UNIX_SLIBCRYPTO)
ZOS31_SLIBSSL			= $(UNIX_SLIBSSL)

#
# ZOS 31 bit ASCII
#
ZOSA31_APP_DIR			= $(UNIX_APP_DIR)
ZOSA31_OPENSSL_LIBS		= $(UNIX_OPENSSL_LIBS)
ZOSA31_SLIBCRYPTO		= $(UNIX_SLIBCRYPTO)
ZOSA31_SLIBSSL			= $(UNIX_SLIBSSL)


# Generate macro's used in build from platform stubs
#
OPENSSL_LIBS 	= $($(OPSYS)_OPENSSL_LIBS)
APP_DIR      	= $($(OPSYS)_APP_DIR)
SLIBCRYPTO   	= $($(OPSYS)_SLIBCRYPTO)
SLIBSSL      	= $($(OPSYS)_SLIBSSL)

A_OBJ    	=  $(APP_DIR)/apps$(OBJSUFX) 
S_OBJ    	=  $(APP_DIR)/s_cb$(OBJSUFX)  $(APP_DIR)/s_socket$(OBJSUFX)
RAND_OBJ 	=  $(APP_DIR)/app_rand$(OBJSUFX)


show_ossl_config:
	echo "E_OBJ        = $(E_OBJ)"
	echo "SLIBCRYPTO   = $(SLIBCRYPTO)"
	echo "SLIBSSL      = $(SLIBSSL)"
	echo "OPENSSL_LIBS = $(OPENSSL_LIBS)"
