# GSkit specific definitions
# Used by various parts of the ICC build to build the correct binaries
# or to locate the built lib to link against it
# Note that this only means we link correctly - runtime is another
# problem.

#
# GSkit version we are building for
GSK_VER		=	8
# Where we park the binaries
GSK_DIR		=	$(ICC_ROOT)/package/gskit_crypto

INST_DIR	=	$(GSK_DIR)

#
# The following may need to be altered to rebuild the regression tests
# in a developer environment
#
# Where we find the header files for using GSkit-crypto
GSK_SDK		=	$(ICC_ROOT)/package/gsk_sdk

#
# Directories for Java version of GSkit_Crypto
#
JGSK_DIR		= $(ICC_ROOT)/package/jgskit_crypto
JGSK_SDK		= $(ICC_ROOT)/package/jgsk_sdk
JINST_DIR               = $(JGSK_DIR)

# Where we find the link time dependencies.
WIN_ICCPKG_LIBS			= $(GSK_SDK)/gsk$(GSK_VER)iccs.lib
UNIX_ICCPKG_LIBS		= -L$(GSK_DIR) -lgsk$(GSK_VER)iccs
UNIX64_ICCPKG_LIBS		= -L$(GSK_DIR) -lgsk$(GSK_VER)iccs_64
# JCEPlus variant
WIN_JCCPKG_LIBS			= $(JGSK_SDK)/lib/jgsk$(GSK_VER)iccs.lib
UNIX_JCCPKG_LIBS		= -L$(JGSK_DIR) -ljgsk$(GSK_VER)iccs
UNIX64_JCCPKG_LIBS		= -L$(JGSK_DIR) -ljgsk$(GSK_VER)iccs_64

# Aux lib for linking
WIN_AUX_LIBS			= $(GSK_SDK)/iccaux$(VTAG).lib
UNIX_AUX_LIBS		   	= -L$(GSK_SDK) -liccaux$(VTAG)
UNIX64_AUX_LIBS			= -L$(GSK_SDK) -liccaux$(VTAG)
# Base library name 
GSKLIB_B               		= $(SHLPRFX)gsk$(GSK_VER)iccs
GSKLIB32			= $(SHLPRFX)gsk$(GSK_VER)iccs$(SHLSUFX)
GSKLIB64			= $(SHLPRFX)gsk$(GSK_VER)iccs_64$(SHLSUFX)
# JCEPlus variant
JGSKLIB_B               	= $(SHLPRFX)jgsk$(GSK_VER)iccs
JGSKLIB32			= $(SHLPRFX)jgsk$(GSK_VER)iccs$(SHLSUFX)
JGSKLIB64			= $(SHLPRFX)jgsk$(GSK_VER)iccs_64$(SHLSUFX)

# default install loc
UNIX_GSK_GLOBAL         	= "/opt/ibm/gsk8/lib"
UNIX64_GSK_GLOBAL         	= "/opt/ibm/gsk8_64/lib64"
LINUX_GSK_GLOBAL        	= "/usr/local/ibm/gsk8/lib"
LINUX64_GSK_GLOBAL         	= "/usr/local/ibm/gsk8_64/lib64"

# Base library name 
WIN32_ICCPKG_LIBS		= $(GSK_SDK)/gsk$(GSK_VER)iccs.lib
WIN32_GSKLIB                  	= $(GSKLIB_B)$(SHLSUFX)
WIN32_JGSKLIB                  	= $(JGSKLIB_B)$(SHLSUFX)
WIN32_JCCPKG_LIBS		= $(JGSK_SDK)/lib/jgsk$(GSK_VER)iccs.lib
WIN32_GSK_SETUP			=  set PATH='$(GSK_DIR);$(PACKAGE_DIR);${PATH}'
WIN32_AUX_LIBS			= $(WIN_AUX_LIBS)

WIN32_VS2013_ICCPKG_LIBS	= $(GSK_SDK)/gsk$(GSK_VER)iccs.lib
WIN32_VS2013_GSKLIB             = $(GSKLIB_B)$(SHLSUFX)
WIN32_VS2013_JGSKLIB            = $(JGSKLIB_B)$(SHLSUFX)
WIN32_VS2013_JCCPKG_LIBS	= $(JGSK_SDK)/lib/jgsk$(GSK_VER)iccs.lib
WIN32_VS2013_GSK_SETUP		=  set PATH='$(GSK_DIR);$(PACKAGE_DIR);${PATH}'
WIN32_VS2013_AUX_LIBS		= $(WIN_AUX_LIBS)

WIN32_VS2022_ICCPKG_LIBS	= $(GSK_SDK)/gsk$(GSK_VER)iccs.lib
WIN32_VS2022_GSKLIB             = $(GSKLIB_B)$(SHLSUFX)
WIN32_VS2022_JGSKLIB            = $(JGSKLIB_B)$(SHLSUFX)
WIN32_VS2022_JCCPKG_LIBS	= $(JGSK_SDK)/lib/jgsk$(GSK_VER)iccs.lib
WIN32_VS2022_GSK_SETUP		=  set PATH='$(GSK_DIR);$(PACKAGE_DIR);${PATH}'
WIN32_VS2022_AUX_LIBS		= $(WIN_AUX_LIBS)

WIN64_ICCPKG_LIBS		= $(GSK_SDK)/gsk$(GSK_VER)iccs_64.lib
WIN64_GSKLIB			= $(GSKLIB_B)_64$(SHLSUFX)
WIN64_JGSKLIB			= $(JGSKLIB_B)_64$(SHLSUFX)
WIN64_JCCPKG_LIBS		= $(JGSK_SDK)/lib/jgsk$(GSK_VER)iccs_64.lib
WIN64_GSK_SETUP			= $(WIN32_GSK_SETUP)
WIN64_AUX_LIBS			= $(WIN_AUX_LIBS)

WIN64_AMD_ICCPKG_LIBS		= $(GSK_SDK)/gsk$(GSK_VER)iccs_64.lib
WIN64_AMD_GSKLIB		= $(GSKLIB_B)_64$(SHLSUFX)
WIN64_AMD_JGSKLIB		= $(JGSKLIB_B)_64$(SHLSUFX)
WIN64_AMD_JCCPKG_LIBS		= $(JGSK_SDK)/lib/jgsk$(GSK_VER)iccs_64.lib
WIN64_AMD_GSK_SETUP		= $(WIN32_GSK_SETUP)
WIN64_AMD_AUX_LIBS		= $(WIN_AUX_LIBS)

WIN64_AMD_VS2013_ICCPKG_LIBS		= $(GSK_SDK)/gsk$(GSK_VER)iccs_64.lib
WIN64_AMD_VS2013_GSKLIB			= $(GSKLIB_B)_64$(SHLSUFX)
WIN64_AMD_VS2013_JGSKLIB		= $(JGSKLIB_B)_64$(SHLSUFX)
WIN64_AMD_VS2013_JCCPKG_LIBS		= $(JGSK_SDK)/lib/jgsk$(GSK_VER)iccs_64.lib
WIN64_AMD_VS2013_GSK_SETUP		= $(WIN32_GSK_SETUP)
WIN64_AMD_VS2013_AUX_LIBS		= $(WIN_AUX_LIBS)

WIN64_VS2022_ICCPKG_LIBS		= $(GSK_SDK)/gsk$(GSK_VER)iccs_64.lib
WIN64_VS2022_GSKLIB			= $(GSKLIB_B)_64$(SHLSUFX)
WIN64_VS2022_JGSKLIB		= $(JGSKLIB_B)_64$(SHLSUFX)
WIN64_VS2022_JCCPKG_LIBS		= $(JGSK_SDK)/lib/jgsk$(GSK_VER)iccs_64.lib
WIN64_VS2022_GSK_SETUP		= $(WIN32_GSK_SETUP)
WIN64_VS2022_AUX_LIBS		= $(WIN_AUX_LIBS)

LINUX_ICCPKG_LIBS		= $(UNIX_ICCPKG_LIBS)
LINUX_GSKLIB			= $(GSKLIB32)
LINUX_JGSKLIB			= $(JGSKLIB32)
LINUX_JCCPKG_LIBS		= $(UNIX_JCCPKG_LIBS)
LINUX_AUX_LIBS			= $(UNIX_AUX_LIBS)

#LINUX_GSK_GLOBAL  See above
# Disabled while we clobber DSA in FIPS mode
#LINUX_GSK_SETUP			= export LD_LIBRARY_PATH=$(GSK_DIR); ./icctest;
LINUX_GSK_SETUP			= export LD_LIBRARY_PATH=$(GSK_DIR)

AMD64_LINUX_ICCPKG_LIBS		= $(UNIX64_ICCPKG_LIBS)
AMD64_LINUX_GSKLIB		= $(GSKLIB64)
AMD64_LINUX_JGSKLIB		= $(JGSKLIB64)
AMD64_LINUX_JCCPKG_LIBS		= $(UNIX64_JCCPKG_LIBS)
AMD64_LINUX_GSK_GLOBAL     	= $(LINUX64_GSK_GLOBAL)
AMD64_LINUX_GSK_SETUP		= $(LINUX_GSK_SETUP)
AMD64_LINUX_AUX_LIBS		= $(UNIX_AUX_LIBS)


ARM_LINUX_ICCPKG_LIBS		= $(UNIX_ICCPKG_LIBS)
ARM_LINUX_GSKLIB		= $(GSKLIB32)
ARM_LINUX_JGSKLIB		= $(JGSKLIB32)
ARM_LINUX_JCCPKG_LIBS		= $(UNIX_JCCPKG_LIBS)
ARM_LINUX_GSK_GLOBAL     	= $(LINUX_GSK_GLOBAL)
ARM_LINUX_GSK_SETUP		= $(LINUX_GSK_SETUP)
ARM_LINUX_AUX_LIBS		= $(UNIX_AUX_LIBS)

ARM64_LINUX_ICCPKG_LIBS		= $(UNIX64_ICCPKG_LIBS)
ARM64_LINUX_GSKLIB		= $(GSKLIB64)
ARM64_LINUX_JGSKLIB		= $(JGSKLIB64)
ARM64_LINUX_JCCPKG_LIBS		= $(UNIX64_JCCPKG_LIBS)
ARM64_LINUX_GSK_GLOBAL     	= $(LINUX64_GSK_GLOBAL)
ARM64_LINUX_GSK_SETUP		= $(LINUX_GSK_SETUP)
ARM64_LINUX_AUX_LIBS		= $(UNIX_AUX_LIBS)

PPC_LINUX_ICCPKG_LIBS		= $(UNIX_ICCPKG_LIBS)
PPC_LINUX_GSKLIB		= $(GSKLIB32)
PPC_LINUX_JGSKLIB		= $(JGSKLIB32)
PPC_LINUX_JCCPKG_LIBS		= $(UNIX_JCCPKG_LIBS)
PPC_LINUX_GSK_GLOBAL       	= $(LINUX_GSK_GLOBAL)
PPC_LINUX_GSK_SETUP		= $(LINUX_GSK_SETUP)
PPC_LINUX_AUX_LIBS		= $(UNIX_AUX_LIBS)

PPC64_LINUX_ICCPKG_LIBS		= $(UNIX64_ICCPKG_LIBS)
PPC64_LINUX_GSKLIB		= $(GSKLIB64)
PPC64_LINUX_JGSKLIB		= $(JGSKLIB64)
PPC64_LINUX_JCCPKG_LIBS		= $(UNIX64_JCCPKG_LIBS)
PPC64_LINUX_GSK_GLOBAL       	= $(LINUX64_GSK_GLOBAL)
PPC64_LINUX_GSK_SETUP		= $(LINUX_GSK_SETUP)
PPC64_LINUX_AUX_LIBS		= $(UNIX_AUX_LIBS)

PPC64LE_LINUX_ICCPKG_LIBS	= $(UNIX64_ICCPKG_LIBS)
PPC64LE_LINUX_GSKLIB		= $(GSKLIB64)
PPC64LE_LINUX_JGSKLIB		= $(JGSKLIB64)
PPC64LE_LINUX_JCCPKG_LIBS	= $(UNIX64_JCCPKG_LIBS)
PPC64LE_LINUX_GSK_GLOBAL       	= $(LINUX64_GSK_GLOBAL)
PPC64LE_LINUX_GSK_SETUP		= $(LINUX_GSK_SETUP)
PPC64LE_LINUX_AUX_LIBS		= $(UNIX_AUX_LIBS)

IA64_LINUX_ICCPKG_LIBS		= $(UNIX64_ICCPKG_LIBS)
IA64_LINUX_GSKLIB		= $(GSKLIB64)
IA64_LINUX_JGSKLIB		= $(JGSKLIB64)
IA64_LINUX_JCCPKG_LIBS		= $(UNIX64_JCCPKG_LIBS)
IA64_LINUX_GSK_GLOBAL       	= $(LINUX64_GSK_GLOBAL)
IA64_LINUX_GSK_SETUP		= $(LINUX_GSK_SETUP)
IA64_LINUX_AUX_LIBS		= $(UNIX_AUX_LIBS)


S390_LINUX_ICCPKG_LIBS		= $(UNIX_ICCPKG_LIBS)
S390_LINUX_GSKLIB		= $(GSKLIB32)
S390_LINUX_JGSKLIB		= $(JGSKLIB32)
S390_LINUX_JCCPKG_LIBS		= $(UNIX_JCCPKG_LIBS)
S390_LINUX_GSK_GLOBAL		= $(LINUX_GSK_GLOBAL)
S390_LINUX_GSK_SETUP		= $(LINUX_GSK_SETUP)
S390_LINUX_AUX_LIBS		= $(UNIX_AUX_LIBS)

S390X_LINUX_ICCPKG_LIBS		= $(UNIX64_ICCPKG_LIBS)
S390X_LINUX_GSKLIB		= $(GSKLIB64)
S390X_LINUX_JGSKLIB		= $(JGSKLIB64)
S390X_LINUX_JCCPKG_LIBS		= $(UNIX64_JCCPKG_LIBS)
S390X_LINUX_GSK_GLOBAL		= $(LINUX64_GSK_GLOBAL)
S390X_LINUX_GSK_SETUP		= $(LINUX_GSK_SETUP)
S390X_LINUX_AUX_LIBS		= $(UNIX_AUX_LIBS)


ZOS_ICCPKG_LIBS				= $(GSK_SDK)/libgsk$(GSK_VER)iccs_64.x
ZOS_GSKLIB				= $(GSKLIB64)
ZOS_JGSKLIB				= $(JGSKLIB64)
ZOS_JCCPKG_LIBS				= $(JGSK_SDK)/libjgsk$(GSK_VER)iccs_64.x
ZOS_GSK_GLOBAL				= $(LINUX_GSK_GLOBAL)
ZOS_GSK_SETUP				= $(LINUX_GSK_SETUP)
ZOS_AUX_LIBS				= $(UNIX_AUX_LIBS)

# ZOS ASCII mode
ZOSA_ICCPKG_LIBS			= $(GSK_SDK)/libgsk$(GSK_VER)iccs_64.x
ZOSA_GSKLIB				= $(GSKLIB64)
ZOSA_JGSKLIB				= $(JGSKLIB64)
ZOSA_JCCPKG_LIBS			= $(JGSK_SDK)/libjgsk$(GSK_VER)iccs_64.x
ZOSA_GSK_GLOBAL				= $(LINUX_GSK_GLOBAL)
ZOSA_GSK_SETUP				= $(LINUX_GSK_SETUP)
ZOSA_AUX_LIBS				= $(UNIX_AUX_LIBS)


ZOS31_ICCPKG_LIBS			= $(GSK_SDK)/libgsk$(GSK_VER)iccs.x
ZOS31_GSKLIB				= $(GSKLIB32)
ZOS31_JGSKLIB				= $(JGSKLIB32)
ZOS31_JCCPKG_LIBS			= $(JGSK_SDK)/libjgsk$(GSK_VER)iccs.x
ZOS31_GSK_GLOBAL			= $(LINUX_GSK_GLOBAL)
ZOS31_GSK_SETUP				= $(LINUX_GSK_SETUP)
ZOS31_AUX_LIBS				= $(UNIX_AUX_LIBS)

# ZOS 31 bit ASCII mode
ZOSA31_ICCPKG_LIBS			= $(GSK_SDK)/libgsk$(GSK_VER)iccs.x
ZOSA31_GSKLIB				= $(GSKLIB32)
ZOSA31_JGSKLIB				= $(JGSKLIB32)
ZOSA31_JCCPKG_LIBS			= $(JGSK_SDK)/libjgsk$(GSK_VER)iccs.x
ZOSA31_GSK_GLOBAL			= $(LINUX_GSK_GLOBAL)
ZOSA31_GSK_SETUP			= $(LINUX_GSK_SETUP)
ZOSA31_AUX_LIBS				= $(UNIX_AUX_LIBS)


OS400X_ICCPKG_LIBS		= $(UNIX_ICCPKG_LIBS)
OS400X_GSKLIB			= $(GSKLIB32)
OS400X_JGSKLIB			= $(JGSKLIB32)
OS400X_JCCPKG_LIBS		= $(UNIX_JCCPKG_LIBS)
OS400X_GSK_GLOBAL		= $(LINUX_GSK_GLOBAL)
OS400X_GSK_SETUP		= $(LINUX_GSK_SETUP)
OS400X_AUX_LIBS			= $(UNIX_AUX_LIBS)


OSX_FAT4_ICCPKG_LIBS		= $(UNIX_ICCPKG_LIBS)
OSX_FAT4_GSKLIB			= $(GSKLIB32)
OSX_FAT4_JGSKLIB			= $(JGSKLIB32)
OSX_FAT4_JCCPKG_LIBS		= $(UNIX_JCCPKG_LIBS)
OSX_FAT4_GSK_GLOBAL		= $(LINUX_GSK_GLOBAL)
OSX_FAT4_GSK_SETUP		= export DYLD_LIBRARY_PATH=$(GSK_DIR)
OSX_FAT4_AUX_LIBS		= $(UNIX_AUX_LIBS)

OSX_X86_ICCPKG_LIBS		= $(UNIX_ICCPKG_LIBS)
OSX_X86_GSKLIB			= $(GSKLIB32)
OSX_X86_GSK_GLOBAL		= $(LINUX_GSK_GLOBAL)
OSX_X86_GSK_SETUP		= export DYLD_LIBRARY_PATH=$(GSK_DIR)
OSX_X86_AUX_LIBS		= $(UNIX_AUX_LIBS)

OSX_X86_64_ICCPKG_LIBS		= $(UNIX_ICCPKG_LIBS)
OSX_X86_64_GSKLIB		= $(GSKLIB64)
OSX_X86_64_GSK_GLOBAL		= $(LINUX_GSK_GLOBAL)
OSX_X86_64_GSK_SETUP		= export DYLD_LIBRARY_PATH=$(GSK_DIR)
OSX_X86_64_AUX_LIBS		= $(UNIX_AUX_LIBS)

OSX_ARM64_ICCPKG_LIBS	= $(UNIX_ICCPKG_LIBS)
OSX_ARM64_GSKLIB		= $(GSKLIB32)
OSX_ARM64_JGSKLIB		= $(JGSKLIB32)
OSX_ARM64_JCCPKG_LIBS	= $(UNIX_JCCPKG_LIBS)
OSX_ARM64_GSK_GLOBAL	= $(LINUX_GSK_GLOBAL)
OSX_ARM64_GSK_SETUP	= export DYLD_LIBRARY_PATH=$(GSK_DIR)
OSX_ARM64_AUX_LIBS		= $(UNIX_AUX_LIBS)

OSXV9_ICCPKG_LIBS		= $(UNIX_ICCPKG_LIBS)
OSXV9_GSKLIB			= $(GSKLIB32)
OSXV9_JGSKLIB			= $(JGSKLIB32)
OSXV9_JCCPKG_LIBS		= $(UNIX_JCCPKG_LIBS)
OSXV9_GSK_GLOBAL		= $(LINUX_GSK_GLOBAL)
OSXV9_GSK_SETUP		= export DYLD_LIBRARY_PATH=$(GSK_DIR)
OSXV9_AUX_LIBS		= $(UNIX_AUX_LIBS)

AIX_ICCPKG_LIBS			= -brtl $(UNIX_ICCPKG_LIBS)
AIX_GSKLIB			= $(GSKLIB32)
AIX_JGSKLIB			= $(JGSKLIB32)
AIX_JCCPKG_LIBS			= -brtl $(UNIX_JCCPKG_LIBS)
AIX_GSK_GLOBAL			= "/usr/opt/ibm/gsk8/lib"
AIX_GSK_SETUP			= export LIBPATH=$(GSK_DIR)
AIX_AUX_LIBS			= $(UNIX_AUX_LIBS)


AIX64_ICCPKG_LIBS		= -brtl $(UNIX64_ICCPKG_LIBS)
AIX64_GSKLIB			= $(GSKLIB64)
AIX64_JGSKLIB			= $(JGSKLIB64)
AIX64_JCCPKG_LIBS		= -brtl $(UNIX64_JCCPKG_LIBS)
AIX64_GSK_GLOBAL		= "/usr/opt/ibm/gsk8_64/lib64"
AIX64_GSK_SETUP			= export LIBPATH=$(GSK_DIR)
AIX64_AUX_LIBS			= $(UNIX_AUX_LIBS)


SUN_ICCPKG_LIBS			= $(UNIX_ICCPKG_LIBS)
SUN_GSKLIB			= $(GSKLIB32)
SUN_JGSKLIB			= $(JGSKLIB32)
SUN_JCCPKG_LIBS			= $(UNIX_JCCPKG_LIBS)
SUN_GSK_GLOBAL			= $(UNIX_GSK_GLOBAL)
SUN_GSK_SETUP			= $(LINUX_GSK_SETUP)
SUN_AUX_LIBS			= $(UNIX_AUX_LIBS)


SUN64_ICCPKG_LIBS		= $(UNIX64_ICCPKG_LIBS)
SUN64_GSKLIB			= $(GSKLIB64)
SUN64_JGSKLIB			= $(JGSKLIB64)
SUN64_JCCPKG_LIBS		= $(UNIX64_JCCPKG_LIBS)
SUN64_GSK_GLOBAL		= $(UNIX64_GSK_GLOBAL)
SUN64_GSK_SETUP			= $(SUN_GSK_SETUP)
SUN64_AUX_LIBS			= $(UNIX_AUX_LIBS)


SUN_AMD64_ICCPKG_LIBS		= $(UNIX64_ICCPKG_LIBS)
SUN_AMD64_GSKLIB		= $(GSKLIB64)
SUN_AMD64_JGSKLIB		= $(JGSKLIB64)
SUN_AMD64_JCCPKG_LIBS		= $(UNIX64_JCCPKG_LIBS)
SUN_AMD64_GSK_GLOBAL		= $(SUN64_GSK_GLOBAL)
SUN_AMD64_GSK_SETUP		= $(SUN_GSK_SETUP)
SUN_AMD64_AUX_LIBS		= $(UNIX_AUX_LIBS)


SUN_X86_ICCPKG_LIBS		= $(UNIX_ICCPKG_LIBS)
SUN_X86_GSKLIB			= $(GSKLIB32)
SUN_X86_JGSKLIB			= $(JGSKLIB32)
SUN_X86_JCCPKG_LIBS		= $(UNIX_JCCPKG_LIBS)
SUN_X86_GSK_GLOBAL		= $(SUN_GSK_GLOBAL)
SUN_X86_GSK_SETUP		= $(SUN_GSK_SETUP)
SUN_X86_AUX_LIBS		= $(UNIX_AUX_LIBS)


HPUX_ICCPKG_LIBS		= $(UNIX_ICCPKG_LIBS)
HPUX_GSKLIB			= $(GSKLIB32)
HPUX_JGSKLIB			= $(JGSKLIB32)
HPUX_JCCPKG_LIBS		= $(UNIX_JCCPKG_LIBS)
HPUX_GSK_GLOBAL			= $(UNIX_GSK_GLOBAL)
HPUX_GSK_SETUP			= $(LINUX_GSK_SETUP)
HPUX_AUX_LIBS			= $(UNIX_AUX_LIBS)


HPUX64_ICCPKG_LIBS		= $(UNIX64_ICCPKG_LIBS)
HPUX64_GSKLIB			= $(GSKLIB64)
HPUX64_JGSKLIB			= $(JGSKLIB64)
HPUX64_JCCPKG_LIBS		= $(UNIX64_JCCPKG_LIBS)
HPUX64_GSK_GLOBAL		= $(UNIX64_GSK_GLOBAL)
HPUX64_GSK_SETUP		= $(LINUX_GSK_SETUP)
HPUX64_AUX_LIBS			= $(UNIX_AUX_LIBS)


IA64_HPUX_ICCPKG_LIBS		= -L$(GSK_DIR) -lgsk$(GSK_VER)iccs_32
IA64_HPUX_GSKLIB		= $(GSKLIB_B)_32$(SHLSUFX)
IA64_HPUX_JGSKLIB		= $(JGSKLIB_B)_32$(SHLSUFX)
IA64_HPUX_JCCPKG_LIBS		= -L$(JGSK_DIR) -ljgsk$(GSK_VER)iccs_32
IA64_HPUX_GSK_GLOBAL		= $(HPUX_GSK_GLOBAL)
IA64_HPUX_GSK_SETUP		= $(LINUX_GSK_SETUP)
IA64_HPUX_AUX_LIBS		= $(UNIX_AUX_LIBS)


IA64_HPUX64_ICCPKG_LIBS		= $(UNIX64_ICCPKG_LIBS)
IA64_HPUX64_GSKLIB		= $(GSKLIB64)
IA64_HPUX64_JGSKLIB		= $(JGSKLIB64)
IA64_HPUX64_JCCPKG_LIBS		= $(UNIX64_JCCPKG_LIBS)
IA64_HPUX64_GSK_GLOBAL		= $(HPUX64_GSK_GLOBAL)
IA64_HPUX64_GSK_SETUP		= $(LINUX_GSK_SETUP)
IA64_HPUX64_AUX_LIBS		= $(UNIX_AUX_LIBS)


# Names of the GSkit-crypto libs for GSkit8
GSK_LIBNAME 			= $($(OPSYS)_GSKLIB)
GSK_LIB				= $(GSK_DIR)/$(GSK_LIBNAME)
ICCPKG_LIBS			= $($(OPSYS)_ICCPKG_LIBS)
# Names of the GSkit-Crypto libs for Java components
JGSK_LIBNAME 			= $($(OPSYS)_JGSKLIB)
JGSK_LIB			= $(JGSK_DIR)/$(JGSK_LIBNAME)
JCCPKG_LIBS			= $($(OPSYS)_JCCPKG_LIBS)
# Global GSkit install dir
GSK_GLOBAL			= $($(OPSYS)_GSK_GLOBAL)
# LD_LIBRARY_PATH setup to find libs at runtume
GSK_SETUP			= $($(OPSYS)_GSK_SETUP)
# Link path to the aux library
AUX_LIBS			= $($(OPSYS)_AUX_LIBS)
