# Makefile stub containing the hacks needed to build gskit-crypto


WIN32_ICCPKG_EXPFILE            	= exports/iccstepwin.def
WIN32_JCCPKG_EXPFILE            	= exports/jccstepwin.def 
WIN32_JCCPKG_EXPFILE            	= exports/jccstepwin.def
WIN32_ICCAUX_EXPFILE					= exports/iccauxwin.def


WIN64_AMD_ICCPKG_EXPFILE        	= $(WIN32_ICCPKG_EXPFILE)
WIN64_AMD_JCCPKG_EXPFILE        	= $(WIN32_JCCPKG_EXPFILE)
WIN64_AMD_ICCAUX_EXPFILE        	= $(WIN32_ICCAUX_EXPFILE)


WIN32_VS2013_ICCPKG_EXPFILE		= exports/iccstepwin.def
WIN32_VS2013_JCCPKG_EXPFILE		= exports/jccstepwin.def
WIN32_VS2013_ICCAUX_EXPFILE		= exports/iccauxwin.def

WIN32_VS2022_ICCPKG_EXPFILE		= $(WIN32_ICCPKG_EXPFILE)
WIN32_VS2022_JCCPKG_EXPFILE		= $(WIN32_JCCPKG_EXPFILE)
WIN32_VS2022_ICCAUX_EXPFILE		= $(WIN32_ICCAUX_EXPFILE)

WIN64_AMD_VS2013_ICCPKG_EXPFILE        = $(WIN32_ICCPKG_EXPFILE)
WIN64_AMD_VS2013_JCCPKG_EXPFILE        = $(WIN32_JCCPKG_EXPFILE)
WIN64_AMD_VS2013_ICCAUX_EXPFILE        = $(WIN32_ICCAUX_EXPFILE)
WIN64_AMD_VS2013_ICCPKG_OLD_EXPFILE    = $(WIN32_ICCPKG_OLD_EXPFILE)

WIN64_AMD_VS2019_ICCPKG_EXPFILE        = $(WIN32_ICCPKG_EXPFILE)
WIN64_AMD_VS2019_JCCPKG_EXPFILE        = $(WIN32_JCCPKG_EXPFILE)
WIN64_AMD_VS2019_ICCAUX_EXPFILE        = $(WIN32_ICCAUX_EXPFILE)
WIN64_AMD_VS2019_ICCPKG_OLD_EXPFILE    = $(WIN32_ICCPKG_OLD_EXPFILE)




WIN64_VS2022_ICCPKG_EXPFILE        = $(WIN32_ICCPKG_EXPFILE)
WIN64_VS2022_JCCPKG_EXPFILE        = $(WIN32_JCCPKG_EXPFILE)
WIN64_VS2022_ICCAUX_EXPFILE        = $(WIN32_ICCAUX_EXPFILE)

LINUX_ICCPKG_EXPFILE            = exports/iccsteplinux.exp
LINUX_JCCPKG_EXPFILE            = exports/jccsteplinux.exp
LINUX_ICCAUX_EXPFILE            = exports/iccauxlinux.exp


AMD64_LINUX_ICCPKG_EXPFILE      = $(LINUX_ICCPKG_EXPFILE)
AMD64_LINUX_JCCPKG_EXPFILE      = $(LINUX_JCCPKG_EXPFILE)
AMD64_LINUX_ICCAUX_EXPFILE      = $(LINUX_ICCAUX_EXPFILE)


ARM_LINUX_ICCPKG_EXPFILE      	= $(LINUX_ICCPKG_EXPFILE)
ARM_LINUX_JCCPKG_EXPFILE      	= $(LINUX_JCCPKG_EXPFILE)
ARM_LINUX_ICCAUX_EXPFILE      	= $(LINUX_ICCAUX_EXPFILE)


ARM64_LINUX_ICCPKG_EXPFILE      = $(LINUX_ICCPKG_EXPFILE)
ARM64_LINUX_JCCPKG_EXPFILE      = $(LINUX_JCCPKG_EXPFILE)
ARM64_LINUX_ICCAUX_EXPFILE      = $(LINUX_ICCAUX_EXPFILE)


PPC_LINUX_ICCPKG_EXPFILE        = $(LINUX_ICCPKG_EXPFILE)
PPC_LINUX_JCCPKG_EXPFILE        = $(LINUX_JCCPKG_EXPFILE)
PPC_LINUX_ICCAUX_EXPFILE        = $(LINUX_ICCAUX_EXPFILE)


PPC64_LINUX_ICCPKG_EXPFILE      = $(LINUX_ICCPKG_EXPFILE)
PPC64_LINUX_JCCPKG_EXPFILE      = $(LINUX_JCCPKG_EXPFILE)
PPC64_LINUX_ICCAUX_EXPFILE      = $(LINUX_ICCAUX_EXPFILE)


PPC64LE_LINUX_ICCPKG_EXPFILE      	= $(LINUX_ICCPKG_EXPFILE)
PPC64LE_LINUX_JCCPKG_EXPFILE      	= $(LINUX_JCCPKG_EXPFILE)
PPC64LE_LINUX_ICCAUX_EXPFILE      	= $(LINUX_ICCAUX_EXPFILE)


IA64_LINUX_ICCPKG_EXPFILE	= $(LINUX_ICCPKG_EXPFILE)
IA64_LINUX_JCCPKG_EXPFILE	= $(LINUX_JCCPKG_EXPFILE)
IA64_LINUX_ICCAUX_EXPFILE	= $(LINUX_ICCAUX_EXPFILE)


S390_LINUX_ICCPKG_EXPFILE	= $(LINUX_ICCPKG_EXPFILE)
S390_LINUX_JCCPKG_EXPFILE	= $(LINUX_JCCPKG_EXPFILE)
S390_LINUX_ICCAUX_EXPFILE	= $(LINUX_ICCAUX_EXPFILE)


S390X_LINUX_ICCPKG_EXPFILE	= $(LINUX_ICCPKG_EXPFILE)
S390X_LINUX_JCCPKG_EXPFILE	= $(LINUX_JCCPKG_EXPFILE)
S390X_LINUX_ICCAUX_EXPFILE	= $(LINUX_ICCAUX_EXPFILE)


# OSX Components
# Partial build here so these don't need to be complete

OSX_X86_ICCPKG_EXPFILE		= $(LINUX_ICCPKG_EXPFILE)
OSX_X86_JCCPKG_EXPFILE		= $(LINUX_JCCPKG_EXPFILE)


OSX_X86_64_ICCPKG_EXPFILE	= $(LINUX_ICCPKG_EXPFILE)
OSX_X86_64_JCCPKG_EXPFILE	= $(LINUX_JCCPKG_EXPFILE)


ZOS_ICCPKG_EXPFILE		= exports/iccstepZOS.h
ZOS_JCCPKG_EXPFILE		= exports/jccstepZOS.h
ZOS_ICCAUX_EXPFILE		= exports/iccauxZOS.h


ZOSA_ICCPKG_EXPFILE		= exports/iccstepZOS.h
ZOSA_JCCPKG_EXPFILE		= exports/jccstepZOS.h
ZOSA_ICCAUX_EXPFILE		= exports/iccauxZOS.h

ZOS31_ICCPKG_EXPFILE		= exports/iccstepZOS.h
ZOS31_JCCPKG_EXPFILE		= exports/jccstepZOS.h
ZOS31_ICCAUX_EXPFILE		= exports/iccauxZOS.h

ZOSA31_ICCPKG_EXPFILE		= exports/iccstepZOS.h
ZOSA31_JCCPKG_EXPFILE		= exports/jccstepZOS.h
ZOSA31_ICCAUX_EXPFILE		= exports/iccauxZOS.h



OS400X_ICCPKG_EXPFILE		= exports/iccstepOS400.exp
OS400X_JCCPKG_EXPFILE		= exports/jccstepOS400.exp
OS400X_ICCAUX_EXPFILE		= exports/iccauxOS400.exp


OSX_FAT4_EXPORT_FLAG		= -exported_symbols_list 
OSX_FAT4_ICCPKG_EXPFILE         = exports/iccstepOSX.def
OSX_FAT4_JCCPKG_EXPFILE         = exports/jccstepOSX.def
OSX_FAT4_ICCAUX_EXPFILE         = exports/iccauxOSX.def

OSXV9_EXPORT_FLAG		= -exported_symbols_list 
OSXV9_ICCPKG_EXPFILE         = exports/iccstepOSX.def
OSXV9_JCCPKG_EXPFILE         = exports/jccstepOSX.def
OSXV9_ICCAUX_EXPFILE         = exports/iccauxOSX.def

OSX_ARM64_EXPORT_FLAG		= -exported_symbols_list 
OSX_ARM64_ICCPKG_EXPFILE   = exports/iccstepOSX.def
OSX_ARM64_JCCPKG_EXPFILE   = exports/jccstepOSX.def
OSX_ARM64_ICCAUX_EXPFILE   = exports/iccauxOSX.def

AIX_ICCPKG_EXPFILE              = exports/iccstepaix4.exp
AIX_JCCPKG_EXPFILE              = exports/jccstepaix4.exp
AIX_ICCAUX_EXPFILE              = exports/iccauxaix4.exp


AIX64_ICCPKG_EXPFILE            = $(AIX_ICCPKG_EXPFILE)
AIX64_JCCPKG_EXPFILE            = $(AIX_JCCPKG_EXPFILE)
AIX64_ICCAUX_EXPFILE            = $(AIX_ICCAUX_EXPFILE)



SUN_ICCPKG_EXPFILE              = exports/iccstepsun64.exp
SUN_JCCPKG_EXPFILE              = exports/jccstepsun64.exp
SUN_ICCAUX_EXPFILE              = exports/iccauxsun64.exp


SUN64_ICCPKG_EXPFILE            = $(SUN_ICCPKG_EXPFILE)
SUN64_JCCPKG_EXPFILE            = $(SUN_JCCPKG_EXPFILE)
SUN64_ICCAUX_EXPFILE            = $(SUN_ICCAUX_EXPFILE)


SUN_AMD64_ICCPKG_EXPFILE	= $(SUN_ICCPKG_EXPFILE)
SUN_AMD64_JCCPKG_EXPFILE	= $(SUN_JCCPKG_EXPFILE)
SUN_AMD64_ICCAUX_EXPFILE        = $(SUN_ICCAUX_EXPFILE)


SUN_X86_ICCPKG_EXPFILE		= $(SUN_ICCPKG_EXPFILE)
SUN_X86_JCCPKG_EXPFILE		= $(SUN_JCCPKG_EXPFILE)
SUN_X86_ICCAUX_EXPFILE          = $(SUN_ICCAUX_EXPFILE)



HPUX_ICCPKG_EXPFILE             = exports/iccstephpux.exp
HPUX_JCCPKG_EXPFILE             = exports/jccstephpux.exp
HPUX_ICCAUX_EXPFILE             = exports/iccauxhpux.exp


HPUX64_ICCPKG_EXPFILE           = $(HPUX_ICCPKG_EXPFILE)
HPUX64_JCCPKG_EXPFILE           = $(HPUX_JCCPKG_EXPFILE)
HPUX64_ICCAUX_EXPFILE           = $(HPUX_ICCAUX_EXPFILE)


IA64_HPUX_ICCPKG_EXPFILE	= $(HPUX_ICCPKG_EXPFILE)
IA64_HPUX_JCCPKG_EXPFILE	= $(HPUX_JCCPKG_EXPFILE)
IA64_HPUX_ICCAUX_EXPFILE        = $(HPUX_ICCAUX_EXPFILE)


IA64_HPUX64_ICCPKG_EXPFILE	= $(HPUX_ICCPKG_EXPFILE)
IA64_HPUX64_JCCPKG_EXPFILE	= $(HPUX_JCCPKG_EXPFILE)
IA64_HPUX64_ICCAUX_EXPFILE      = $(HPUX_ICCAUX_EXPFILE)


ICCPKG_EXPFILE                  = $($(OPSYS)_ICCPKG_EXPFILE)
JCCPKG_EXPFILE                  = $($(OPSYS)_JCCPKG_EXPFILE)
ICCAUX_EXPFILE                  = $($(OPSYS)_ICCAUX_EXPFILE)


